version: 2.1

orbs:
  node: circleci/node@5.0.2
  gh: circleci/github-cli@2.0

jobs:
  pack-tarballs:
    docker:
      - image: cimg/base:stable
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full libsecret-1-dev
      - checkout
      - node/install:
          install-yarn: true
          node-version: '18' 
      - run: node --version
      - node/install-packages:
          pkg-manager: yarn
          override-ci-command: yarn install --frozen-lockfile
      - run:
          name: Pack tarballs
          command: |
            yarn oclif pack tarballs
      - run: 
          name: Delete non-tarball files
          command: |
            find dist -type f -not -name '*.tar.gz' -not -name '*.tar.xz' -not -name '*.buildmanifest' -delete
      - store_artifacts:
          path: dist

  pack-windows:
    docker:
      - image: cimg/base:stable
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y nsis p7zip-full libsecret-1-dev
      - checkout
      - node/install:
          install-yarn: true
          node-version: '18' 
      - run: node --version
      - node/install-packages:
          pkg-manager: yarn
          override-ci-command: yarn install --frozen-lockfile
      - run:
          name: Pack Windows Installer
          command: |
            yarn oclif pack win
      - store_artifacts:
          path: dist/win32

  pack-mac:
    docker:
      - image: cimg/base:stable
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y libsecret-1-dev
      - checkout
      - node/install:
          install-yarn: true
          node-version: '18' 
      - run: node --version
      - node/install-packages:
          pkg-manager: yarn
          override-ci-command: yarn install --frozen-lockfile
      - run:
          name: Pack MacOS Installer
          command: |
            yarn oclif pack macos
      - store_artifacts:
          path: dist/macos

  pack-deb:
    docker:
      - image: cimg/base:stable
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y apt-utils libsecret-1-dev
      - checkout
      - node/install:
          install-yarn: true
          node-version: '18' 
      - run: node --version
      - node/install-packages:
          pkg-manager: yarn
          override-ci-command: yarn install --frozen-lockfile
      - run:
          name: Pack Debian Installer
          command: |
            yarn oclif pack deb
      - store_artifacts:
          path: dist/deb

workflows:
  build:
    jobs:
      - pack-windows