version: 2.1

orbs:
  node: circleci/node@5.0.2
  gh: circleci/github-cli@2.0
  aws-cli: circleci/aws-cli@4.1.3

jobs:
  pack-tarballs:
    docker:
      - image: cimg/base:stable
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full libsecret-1-dev
      - checkout
      - node/install:
          install-yarn: true
          node-version: '18' 
      - run: node --version
      - node/install-packages:
          pkg-manager: yarn
          override-ci-command: yarn install --frozen-lockfile
      - run:
          name: Pack tarballs
          command: |
            yarn oclif pack tarballs
      - run: 
          name: Delete non-tarball files
          command: |
            find dist -type f -not -name '*.tar.gz' -not -name '*.tar.xz' -not -name '*.buildmanifest' -delete
      - run:
          name: Upload Tarballs
          command: |
            yarn oclif upload tarballs

  pack-windows:
    docker:
      - image: cimg/base:stable
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y nsis p7zip-full libsecret-1-dev
      - checkout
      - node/install:
          install-yarn: true
          node-version: '18' 
      - run: node --version
      - node/install-packages:
          pkg-manager: yarn
          override-ci-command: yarn install --frozen-lockfile
      - run:
          name: Pack Windows Installer
          command: |
            yarn oclif pack win
      - run:
          name: Upload Windows Installer
          command: |
            yarn oclif upload win

  pack-mac:
    docker:
      - image: cimg/base:stable
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y libsecret-1-dev
      - checkout
      - node/install:
          install-yarn: true
          node-version: '18' 
      - run: node --version
      - node/install-packages:
          pkg-manager: yarn
          override-ci-command: yarn install --frozen-lockfile
      - run:
          name: Pack MacOS Installer
          command: |
            yarn oclif pack macos
      - run:
          name: Upload MacOS Installer
          command: |
            yarn oclif upload macos

  pack-deb:
    docker:
      - image: cimg/base:stable
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y apt-utils libsecret-1-dev
      - aws-cli/install
      - checkout
      - node/install:
          install-yarn: true
          node-version: '18' 
      - run: node --version
      - node/install-packages:
          pkg-manager: yarn
          override-ci-command: yarn install --frozen-lockfile
      - run:
          name: Pack Debian Installer
          command: |
            yarn oclif pack deb
      - run:
          name: Update install.sh
          command: |
            aws s3 cp src/scripts/install.sh s3://rmagent/install.sh
      - run:
          name: Upload Debian Installer
          command: |
            aws s3 cp dist/deb s3://rmagent/apt --recursive
workflows:
  build:
    jobs:
      - pack-windows:
          filters:
            branches:
              only:
                - main
            tags:
              only: /^v.*/
      - pack-tarballs:
          filters:
            branches:
              only:
                - main
            tags:
              only: /^v.*/
      # These are disabled until we setup code signing on CircleCI
      # - pack-deb:
      #     filters:
      #       branches:
      #         only:
      #           - main
      #       tags:
      #         only: /^v.*/
      # - pack-mac:
      #     filters:
      #       branches:
      #         only:
      #           - main
      #       tags:
      #         only: /^v.*/