version: 2.1

parameters:
  channel:
    type: string
    default: ""
    description: Release channel to publish to. "stable" or "beta".
  release_target:
    type: string
    default: "all"
    description: Release target to build. One of "all", "win32-x64", "darwin-x64", "darwin-arm64", "linux-x64", or "linux-arm64".

orbs:
  node: circleci/node@5.0.2
  gh: circleci/github-cli@2.0
  aws-cli: circleci/aws-cli@4.1.3

commands:
  prep-env:
    description: "Prepare environment"
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Load Workspace Variables
          command: cat bash.env > $BASH_ENV
      - node/install:
          install-yarn: false
          node-version: '22'
      - run:
          name: Check Node Version
          command: node --version
      - run:
          name: Enable Corepack Yarn
          command: |
            corepack enable
            yarn --version

  install-packages-generic:
    description: "Install Node Packages"
    steps:
      - run:
          name: Install Node Packages
          command: yarn install --frozen-lockfile --network-timeout 600000

  install-packages-targeted:
    description: "Install Node Packages for a Specific Target"
    parameters:
      platform:
        type: string
      arch:
        type: string
    steps:
      - run:
          name: Install Node Packages for << parameters.platform >>-<< parameters.arch >>
          command: |
            rm -rf node_modules
            npm_config_arch=<< parameters.arch >> \
            npm_config_platform=<< parameters.platform >> \
            npm_config_target_arch=<< parameters.arch >> \
            npm_config_target_platform=<< parameters.platform >> \
            yarn install --frozen-lockfile --network-timeout 600000

  install-linux-deps:
    description: "Install Linux Packaging Dependencies"
    steps:
      - run:
          name: Update & Install Packages
          command: |
            sudo apt-get update
            sudo apt-get install -y apt-utils nsis p7zip-full libsecret-1-dev

  install-macos-certs:
    description: "Install MacOS Signing Certificates"
    steps:
      - run:
          name: Install Certs
          command: |
            INSTALLER_CERTIFICATE="${TMPDIR}/installer_certificate.p12"
            APPLICATION_CERTIFICATE="${TMPDIR}/application_certificate.p12"
            OSX_KEYCHAIN="${TMPDIR}/app-signing.keychain-db"
            echo "export OSX_KEYCHAIN=${OSX_KEYCHAIN}" >> $BASH_ENV
            echo -n "$OSX_INSTALLER_CERT_BASE64" | base64 --decode --output $INSTALLER_CERTIFICATE
            echo -n "$OSX_APPLICATION_CERT_BASE64" | base64 --decode --output $APPLICATION_CERTIFICATE
            OSX_KEYCHAIN_PASSWORD=`openssl rand -hex 12`
            echo "export OSX_KEYCHAIN_PASSWORD=${OSX_KEYCHAIN_PASSWORD}" >> $BASH_ENV
            security create-keychain -p "$OSX_KEYCHAIN_PASSWORD" $OSX_KEYCHAIN
            security unlock-keychain -p "$OSX_KEYCHAIN_PASSWORD" $OSX_KEYCHAIN
            security set-keychain-settings -lut 21600 $OSX_KEYCHAIN
            security import $INSTALLER_CERTIFICATE -k $OSX_KEYCHAIN -f pkcs12 -A -T /usr/bin/codesign -T /usr/bin/security -P "$OSX_INSTALLER_CERT_PASSWORD"
            security import $APPLICATION_CERTIFICATE -k $OSX_KEYCHAIN -f pkcs12 -A -T /usr/bin/codesign -T /usr/bin/security -P "$OSX_APPLICATION_CERT_PASSWORD"
            security set-key-partition-list -S apple-tool:,apple: -k "$OSX_KEYCHAIN_PASSWORD" $OSX_KEYCHAIN
            security list-keychains -d user -s $OSX_KEYCHAIN login.keychain
            security find-identity

jobs:
  prepare-release:
    parameters:
      manual_release_channel:
        type: string
        default: ""
      manual_release_version:
        type: string
        default: ""
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Determine Tag, Commit SHA, and Prepare Release Info
          command: |
            CURRENT_TAG=$(git describe --tags --exact-match 2>/dev/null || true)
            RELEASE_VERSION=$(jq -r .version package.json)
            if [ -n "$CURRENT_TAG" ]; then
              RELEASE_CHANNEL="stable"
            else
              RELEASE_CHANNEL="beta"
            fi

            if [ -n "<< parameters.manual_release_channel >>" ]; then
              RELEASE_CHANNEL="<< parameters.manual_release_channel >>"
            fi

            echo "export RELEASE_CHANNEL=${RELEASE_CHANNEL}" >> $BASH_ENV
            echo "export RELEASE_VERSION=${RELEASE_VERSION}" >> $BASH_ENV
            echo "export COMMIT_SHA=$(git rev-parse --short HEAD)" >> $BASH_ENV
            source $BASH_ENV

            cp $BASH_ENV bash.env

            echo "Configured Release Channel: $RELEASE_CHANNEL"
            echo "Configured Release Version: $RELEASE_VERSION"
            echo "Commit SHA: $COMMIT_SHA"
      - persist_to_workspace:
          root: .
          paths:
            - bash.env

  pack-windows-tarball:
    parameters:
      npm_arch:
        type: string
      target:
        type: string
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - prep-env
      - install-linux-deps
      - install-packages-targeted:
          arch: << parameters.npm_arch >>
          platform: win32
      - run:
          name: Pack Windows Tarball << parameters.target >>
          command: |
            yarn oclif pack tarballs --targets << parameters.target >> --xz
      - run:
          name: Upload Windows Tarball << parameters.target >>
          command: |
            yarn oclif upload tarballs --targets << parameters.target >> --xz

  pack-windows-installer:
    parameters:
      npm_arch:
        type: string
      target:
        type: string
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - prep-env
      - install-linux-deps
      - install-packages-targeted:
          arch: << parameters.npm_arch >>
          platform: win32
      - run:
          name: Pack Windows Installer << parameters.target >>
          command: |
            npm_config_arch=<< parameters.npm_arch >> \
            npm_config_platform=win32 \
            npm_config_target_arch=<< parameters.npm_arch >> \
            npm_config_target_platform=win32 \
            yarn oclif pack win --targets << parameters.target >>
      - run:
          name: Upload Windows Installer << parameters.target >>
          command: |
            yarn oclif upload win --targets << parameters.target >>

  pack-mac-tarball:
    parameters:
      npm_arch:
        type: string
      target:
        type: string
    macos:
      xcode: 26.4.0
    steps:
      - prep-env
      - install-macos-certs
      - install-packages-targeted:
          arch: << parameters.npm_arch >>
          platform: darwin
      - run:
          name: Pack MacOS Tarball << parameters.target >>
          command: |
            yarn oclif pack tarballs --targets << parameters.target >> --xz
      - run:
          name: Upload MacOS Tarball << parameters.target >>
          command: |
            yarn oclif upload tarballs --targets << parameters.target >> --xz

  pack-mac-installer:
    parameters:
      npm_arch:
        type: string
      target:
        type: string
    macos:
      xcode: 26.4.0
    steps:
      - prep-env
      - install-macos-certs
      - install-packages-targeted:
          arch: << parameters.npm_arch >>
          platform: darwin
      - run:
          name: Pack MacOS Installer << parameters.target >>
          command: |
            npm_config_arch=<< parameters.npm_arch >> \
            npm_config_platform=darwin \
            npm_config_target_arch=<< parameters.npm_arch >> \
            npm_config_target_platform=darwin \
            yarn oclif pack macos --targets << parameters.target >>
      - run:
          name: Notarize MacOS Installer << parameters.target >>
          command: |
            xcrun notarytool store-credentials new-profile --apple-id "$APPLE_ID" --password "$APPLE_ID_APP_PASSWORD" --team-id "$APPLE_TEAM_ID" --keychain "$OSX_KEYCHAIN"

            for FILE_PATH in dist/macos/*.pkg; do
                echo "Notarizing $FILE_PATH..."
                pkgutil --check-signature "$FILE_PATH"
                xcrun notarytool submit "$FILE_PATH" --keychain "$OSX_KEYCHAIN" --keychain-profile new-profile --wait -f json > "${TMPDIR}/notarization_log.json"
                notarization_status=$(jq -r .status "${TMPDIR}/notarization_log.json")
                notarization_id=$(jq -r .id "${TMPDIR}/notarization_log.json")
                echo "For notarization id ${notarization_id} the status is ${notarization_status}"

                if [ "${notarization_status}" = "Accepted" ]; then
                  echo "Stapling $FILE_PATH..."
                  xcrun stapler staple "$FILE_PATH"
                  spctl --assess -vv --type install "$FILE_PATH"
                else
                  echo "Notarization unsuccessful for $FILE_PATH"
                  xcrun notarytool log ${notarization_id} --keychain "$OSX_KEYCHAIN" --keychain-profile new-profile "${TMPDIR}/notarization_log.json"
                  jq . "${TMPDIR}/notarization_log.json"
                  exit 1
                fi
            done
      - run:
          name: Upload MacOS Installer << parameters.target >>
          command: |
            yarn oclif upload macos --targets << parameters.target >>

  pack-linux-tarball:
    parameters:
      npm_arch:
        type: string
      target:
        type: string
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - prep-env
      - install-linux-deps
      - install-packages-targeted:
          arch: << parameters.npm_arch >>
          platform: linux
      - run:
          name: Pack Linux Tarball << parameters.target >>
          command: |
            yarn oclif pack tarballs --targets << parameters.target >> --xz
      - run:
          name: Upload Linux Tarball << parameters.target >>
          command: |
            yarn oclif upload tarballs --targets << parameters.target >> --xz

  promote-windows-release:
    parameters:
      target:
        type: string
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - prep-env
      - install-packages-generic
      - run:
          name: Promote Windows Release << parameters.target >>
          command: |
            yarn oclif promote --channel $RELEASE_CHANNEL --version $RELEASE_VERSION --sha $COMMIT_SHA --indexes --xz --win --targets << parameters.target >>

  promote-mac-release:
    parameters:
      target:
        type: string
    macos:
      xcode: 26.4.0
    steps:
      - prep-env
      - install-packages-generic
      - run:
          name: Promote MacOS Release << parameters.target >>
          command: |
            yarn oclif promote --channel $RELEASE_CHANNEL --version $RELEASE_VERSION --sha $COMMIT_SHA --indexes --xz --macos --targets << parameters.target >>

  promote-linux-release:
    parameters:
      include_deb:
        type: boolean
        default: false
      npm_arch:
        type: string
      target:
        type: string
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - prep-env
      - install-linux-deps
      - install-packages-targeted:
          arch: << parameters.npm_arch >>
          platform: linux
      - run:
          name: Promote Linux Tarball Release << parameters.target >>
          command: |
            yarn oclif promote --channel $RELEASE_CHANNEL --version $RELEASE_VERSION --sha $COMMIT_SHA --indexes --xz --targets << parameters.target >>
      - when:
          condition:
            and:
              - equal: [ true, << parameters.include_deb >> ]
              - not:
                  equal: [ stable, << pipeline.parameters.channel >> ]
              - equal: [ "", << pipeline.git.tag >> ]
          steps:
            - run:
                name: Check Debian Package Creation
                command: |
                  echo "Channel is not stable and no tag is present. Skipping Debian package creation."
      - when:
          condition:
            or:
              - and:
                  - equal: [ true, << parameters.include_deb >> ]
                  - not:
                      equal: [ "", << pipeline.git.tag >> ]
              - and:
                  - equal: [ true, << parameters.include_deb >> ]
                  - equal: [ stable, << pipeline.parameters.channel >> ]
          steps:
            - aws-cli/install
            - run:
                name: Import GPG Key
                command: |
                  echo -n "$GPG_PRIVATE_KEY" | base64 --decode | gpg --batch --import
            - run:
                name: Unlock Keychain
                command: |
                  echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
                  gpg-connect-agent reloadagent /bye
                  echo "$GPG_PASSPHRASE" | gpg -vv --batch --pinentry-mode loopback --passphrase-fd 0 --output /dev/null --sign
            - run:
                name: Pack Debian Installer
                command: |
                  yarn oclif pack deb
            - run:
                name: Update install.sh
                command: |
                  aws s3 cp scripts/install.sh s3://rmagent/install.sh
            - run:
                name: Upload Debian Installer
                command: |
                  aws s3 cp dist/deb s3://rmagent/apt --recursive
            - run:
                name: Upload Release Key
                command: |
                  echo -n "$GPG_PUBLIC_KEY" | base64 --decode > Release.key
                  aws s3 cp Release.key s3://rmagent/apt/Release.key

workflows:
  build_and_release:
    when:
      or:
        - not:
            equal: [ "", << pipeline.git.tag >> ]
        - not:
            equal: [ "", << pipeline.parameters.channel >> ]
    jobs:
      - prepare-release:
          manual_release_channel: << pipeline.parameters.channel >>

      - pack-windows-tarball:
          name: pack-windows-x64-tarball
          npm_arch: x64
          requires:
            - prepare-release
          when:
            or:
              - equal: [ "all", << pipeline.parameters.release_target >> ]
              - equal: [ "win32-x64", << pipeline.parameters.release_target >> ]
          target: win32-x64
      - pack-windows-installer:
          name: pack-windows-x64-installer
          npm_arch: x64
          requires:
            - pack-windows-x64-tarball
          when:
            or:
              - equal: [ "all", << pipeline.parameters.release_target >> ]
              - equal: [ "win32-x64", << pipeline.parameters.release_target >> ]
          target: win32-x64
      - promote-windows-release:
          target: win32-x64
          requires:
            - pack-windows-x64-tarball
            - pack-windows-x64-installer
          when:
            or:
              - equal: [ "all", << pipeline.parameters.release_target >> ]
              - equal: [ "win32-x64", << pipeline.parameters.release_target >> ]

      - pack-mac-tarball:
          name: pack-mac-x64-tarball
          npm_arch: x64
          requires:
            - prepare-release
          when:
            or:
              - equal: [ "all", << pipeline.parameters.release_target >> ]
              - equal: [ "darwin-x64", << pipeline.parameters.release_target >> ]
          target: darwin-x64
      - pack-mac-tarball:
          name: pack-mac-arm64-tarball
          npm_arch: arm64
          requires:
            - prepare-release
          when:
            or:
              - equal: [ "all", << pipeline.parameters.release_target >> ]
              - equal: [ "darwin-arm64", << pipeline.parameters.release_target >> ]
          target: darwin-arm64
      - pack-mac-installer:
          name: pack-mac-x64-installer
          npm_arch: x64
          requires:
            - pack-mac-x64-tarball
          when:
            or:
              - equal: [ "all", << pipeline.parameters.release_target >> ]
              - equal: [ "darwin-x64", << pipeline.parameters.release_target >> ]
          target: darwin-x64
      - pack-mac-installer:
          name: pack-mac-arm64-installer
          npm_arch: arm64
          requires:
            - pack-mac-arm64-tarball
          when:
            or:
              - equal: [ "all", << pipeline.parameters.release_target >> ]
              - equal: [ "darwin-arm64", << pipeline.parameters.release_target >> ]
          target: darwin-arm64
      - promote-mac-release:
          name: promote-mac-x64-release
          target: darwin-x64
          requires:
            - pack-mac-x64-tarball
            - pack-mac-x64-installer
          when:
            or:
              - equal: [ "all", << pipeline.parameters.release_target >> ]
              - equal: [ "darwin-x64", << pipeline.parameters.release_target >> ]
      - promote-mac-release:
          name: promote-mac-arm64-release
          target: darwin-arm64
          requires:
            - pack-mac-arm64-installer
            - pack-mac-arm64-tarball
          when:
            or:
              - equal: [ "all", << pipeline.parameters.release_target >> ]
              - equal: [ "darwin-arm64", << pipeline.parameters.release_target >> ]

      - pack-linux-tarball:
          name: pack-linux-x64-tarball
          npm_arch: x64
          requires:
            - prepare-release
          when:
            or:
              - equal: [ "all", << pipeline.parameters.release_target >> ]
              - equal: [ "linux-x64", << pipeline.parameters.release_target >> ]
          target: linux-x64
      - pack-linux-tarball:
          name: pack-linux-arm64-tarball
          npm_arch: arm64
          requires:
            - prepare-release
          when:
            or:
              - equal: [ "all", << pipeline.parameters.release_target >> ]
              - equal: [ "linux-arm64", << pipeline.parameters.release_target >> ]
          target: linux-arm64
      - promote-linux-release:
          name: promote-linux-x64-release
          include_deb: true
          npm_arch: x64
          target: linux-x64
          requires:
            - pack-linux-x64-tarball
          when:
            or:
              - equal: [ "all", << pipeline.parameters.release_target >> ]
              - equal: [ "linux-x64", << pipeline.parameters.release_target >> ]
      - promote-linux-release:
          name: promote-linux-arm64-release
          include_deb: false
          npm_arch: arm64
          target: linux-arm64
          requires:
            - pack-linux-arm64-tarball
          when:
            or:
              - equal: [ "all", << pipeline.parameters.release_target >> ]
              - equal: [ "linux-arm64", << pipeline.parameters.release_target >> ]
